/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MUTTLEY' at '7/4/16 10:00 AM' with Gradle 2.14
 *
 * @author MUTTLEY, @date 7/4/16 10:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
